### ISSUE TITLE
Can't login with Google account

### ISSUE THREAD

**Issue by BioB3** [PichapopRo/project-pantry#221]
## Description
Trying to log in with my Google account gives me an error page. The URL of the login page is https://project-pantry.onrender.com/accounts/login/
## How to Reproduce
- Click the `Login with Google account` Button
- Select your Google account
- Click `Continue`
## More Detail
I can't provide the screenshot because the error page shows the settings.

**Comment by knilios** [comment]
We have fixed the issue. Thank you for your report.
