### ISSUE TITLE
No recipes on the website and no static files

### ISSUE THREAD

**Issue by KhunakornP** [PichapopRo/project-pantry#226]
## **Bug**
The site doesn't have any recipes! nor static files.

## **How To Reproduce**
1. go to [the website](https://project-pantry.onrender.com/)

## **User Specifications**
OS: Windows 10
Browser: Chrome Version 131.0.6778.86

## **Screenshots**
![no recepies](https://github.com/user-attachments/assets/3bcd82fe-23a7-4f78-a794-1ec8af77b549)

**Comment by SariyaP** [comment]
Recipes are added to website.
