### ISSUE TITLE
Load more button not working correctly

### ISSUE THREAD

**Issue by Thanawas-Sirilertsathit** [PichapopRo/project-pantry#232]
Expected behavior : Load more button should disappear after load all recipe.
Current behavior : User can still see and press the load more button.
Step to reproduce : Press load in recipe list page and scroll down and press it again until you get the same result.

<img width="959" alt="image" src="https://github.com/user-attachments/assets/f2d3534d-4fc3-4a17-aafb-d67fa6ff5a2e">

**Comment by SariyaP** [comment]
We decided to delete load more button.
