### ISSUE TITLE
Images do not show in My pending recipe

### ISSUE THREAD

**Issue by Thanawas-Sirilertsathit** [PichapopRo/project-pantry#234]
Expected behavior : show the images properly.
Current behavior : show text instead of images but I already uploaded the images in these recipes.
Step to reproduce
1. Create recipe with image uploaded
2. Go into My Recipe and pending tab
3. See the alt text instead of images

<img width="960" alt="image" src="https://github.com/user-attachments/assets/5eba216c-92d1-4769-abc8-a6a39738db70">

**Comment by SariyaP** [comment]
The problem we have is associated with the deployment service, It is fixed now.
