### ISSUE TITLE
Access to unpublished recipes

### ISSUE THREAD

**Issue by OmegaOoh** [PichapopRo/project-pantry#235]
The recipes that are rejected (either by AI or Admin) can be accessed by their URL for example
https://project-pantry.onrender.com/recipes/43/ is a rejected recipe on Thanawas Account

### Expected Behaviour
I think the rejected recipe should not be accessible by anyone other than the author of the recipes

**Comment by knilios** [comment]
I've fixed the issue by removing the access to the unapproved recipe.

**Comment by knilios** [comment]
Thank you for reporting.
