### ISSUE TITLE
Filter displays all Recipes when no matching results are found

### ISSUE THREAD

**Issue by PHIMNADA024** [PichapopRo/project-pantry#238]
## The problem
When filtering recipes by "Pescatarian" (a type of recipe not currently available), clicking search displays a "Load More Recipe" button. Clicking this button loads all recipes instead of showing a message indicating no recipes match the selected filter. This behavior is misleading and should be addressed by displaying a message like "No recipes found for this type" when no results are available.

## How to reproduce the problem
1. Click the filter button.
2. Select "Pescatarian" as the filter option.
3. Click the search button.
4. Observe that a "Load More Recipe" button appears.
5. Click the button and notice that all recipes are displayed, not just the filtered results.

## Screenshot
![image](https://github.com/user-attachments/assets/077168e4-b8c2-43ff-96e1-077dfadc7602)

**Comment by Thanawas-Sirilertsathit** [comment]
I think this is load more button problem rather than filter problem.

**Comment by Thanawas-Sirilertsathit** [comment]
#232

**Comment by SariyaP** [comment]
We already add message to show if there is no recipe match with the filter.
