### ISSUE TITLE
Same Recipe Show on Both Accepted and Pending

### ISSUE THREAD

**Issue by OmegaOoh** [PichapopRo/project-pantry#246]
![image](https://github.com/user-attachments/assets/dc1360c1-9660-4ba5-bfbf-94d46715ea21)
![image](https://github.com/user-attachments/assets/756899e4-026e-4aee-9c23-cf7e2b462e77)

## Description

Newly added recipe show on both pending and accept tab

## How to reproduce

1. Create recipe (failed to create)
2. Create same recipe (with no picture, passed)
3. Wait and see the results

**Comment by PichapopRo** [comment]
## Why does it happen?
Because when you pressed submit the image upload system was still broken. And it caused Django to create an empty object. So if the image uploading system is fixed, this bug isn't going to happen.
